export const tropas = [
    {
        nombre:'Colonia de Castores',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Castores.png?alt=media&token=fe5bd83f-e98f-4522-b621-9db819fa3fbb',
        promesa:{
            1:'Yo prometo amar a dios y ayudar a cuidar el mundo.',
        },
        oración:'Gracias, Señor Dios, por enseñarnos a compartir. Así sea.',
        ley:{
            1:'Hacer una buena acción sin que nadie lo sepa.'
        },
        normas:'',
        somosTitulo: '¡Ser castor trata de hacer todo tipo de cosas emocionantes!',
        somos:[
            {
                1:'Si tienes entre 4 y 8 años y te gusta tenere muchos amigos, hacer cosas nuevas, y sobre todo, tener un montón de diversión, la colonia de castores es para tí!!!',
                2:'La colonia de castores es la sección del grupo scout conformada por niños y niñas entre 4 y 8 años donde conviven, juegan y aprenden.',
                3:'El programa scout de los castores ofrece muchas actividades divertidas para los castores, como manualidades, juegos, deportes, canciones e historias.',
                4:'Los castores forman parte de una colonia integrada por niños y niñas de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada niño. ',
                5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',
            },
        ],
        adelantoProgresivo:'La colonia de castores cuenta con un adelanto progresivo, donde cada castor alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima:',
        insigniaMaxima:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FGran%20Castor%20Cafe.png?alt=media&token=583e8778-34a7-411c-89c9-d37fa4532332',	
        nombreInsigniaMaxima:'Gran Castor Cafe',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2Famarilla.png?alt=media&token=c76f3de0-e96e-4bba-80e6-d638fbb1b30e',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2Fverde.png?alt=media&token=8c9d3e5b-6449-474b-8faf-b7ef7ef125e2',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2Fazul.png?alt=media&token=c90c05e7-b2ee-42a4-84a2-396879a890a1',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2Frojo.png?alt=media&token=bd798599-0f7e-4846-8c30-e9de7c6b47ad',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2Fblanca.png?alt=media&token=8258f131-f699-476e-8b03-84c0dfa56d52',
        },
        rangos: {
            1: 'Castor Ansioso',
            2: 'Castor Aprendiz',
            3: 'Castor Activo',
            4: 'Castor Trabajador',
            5: 'Castor Amigo',
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FDeportes.png?alt=media&token=1175382d-da88-452b-b540-ea9f99a64416',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FEcologia.png?alt=media&token=2429ed13-79ac-4d85-842f-5b04ac359d9d',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FExpresion%20y%20Comunicacion.png?alt=media&token=fe6367cb-d11c-4da9-b8e2-040263729dd1',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FHumanidades.png?alt=media&token=0494ef08-b057-4ef6-a6ab-6578befd229e',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FSeguridad%20y%20Rescate.png?alt=media&token=c309b078-2f57-4e4b-8c08-d6cd75794210',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FColonia%20de%20Castores%2FTecnologia%20y%20Ciencia.png?alt=media&token=2fd4505d-c97f-4ad8-b39d-aca4ae021b61',
        },
        especialidades: {
            1: 'Deportes',
            2: 'Ecología',
            3: 'Expresión y Comunicación',
            4: 'Humanidades',
            5: 'Seguridad y Rescate',
            6: 'Ciencia y Tecnología',
        },
    },
    {
        nombre:'Manada de Gacelas',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Gacelas.png?alt=media&token=e70e0e22-5254-4254-ad2d-cd3a93d7ebe7',
        promesa:{
            1:'YO PROMETO',
            1:'CUMPLIR CON AMOR',
            1:'MIS DEBERES PARA CON DIOS Y LA PATRIA',
            1:'OBEDECER LA LEY DE LA MANADA Y HACER UNA BUENA ACCION DIARIAMENTE.',
        },
        oración:'Señor, enseñame a ser, humilde en mi persona, a valorar tu ejemplo a servirte con amor y encontrar el camino que me ha de conduciro ante Ti. Así sea.',
        ley:{
            1:'La gacela es atenta, La gacela hace todo bien, con entuciasmo y rapidez',
            2:'La gacela se vence a si misma.'
        },
        normas:{
            1:'La gacela piensa primero en los demás',
            2:'La gacela es digna de confianza',
            3:'La gacela esta alerta',
            4:'La gacela es limpia',
            5:'La gacela es alegre'
        },
        somosTitulo: '¡Ser gacela trata de hacer todo tipo de cosas emocionantes!',
        somos: [
            {
                1:'Si tienes entre 7 y 11 años y te gusta tenere muchos amigos, hacer cosas nuevas, y sobre todo, tener un montón de diversión, la manada de gacelas es para tí!!',
                2:'La manada de gacelas es la sección del grupo scout conformada por niñas entre 7 y 11 años donde conviven, juegan y aprenden. ',
                3:'El programa scout de las gacelas ofrece muchas actividades divertidas para los castores, como manualidades, juegos, deportes, canciones e historias.',
                4:'Las gacelas forman parte de una manada integrada por niñas de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada niña.',
                5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',
            },
        ],
        adelantoProgresivo:'La colonia de castores cuenta con un adelanto progresivo, donde cada castor alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima:',
        insigniaMaxima:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20gacelas%2FArcoiris.png?alt=media&token=cb1e3485-16a3-4303-98ea-efbb49c67f2c',
        nombreInsigniaMaxima:'Arcoiris',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20gacelas%2FPiel%20Cafe.png?alt=media&token=284977de-9919-4ca8-b683-9eedea38c185',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20gacelas%2FBosque.png?alt=media&token=a8eb6857-ec3d-445b-8d21-6c4aea21731b',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20gacelas%2FPradera.png?alt=media&token=94bbc43c-a97f-4273-8c7a-d93daf1b998f',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20gacelas%2FPiel%20Roja.png?alt=media&token=1957fb8c-b062-434a-a68c-1f17999022cb',
            
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FDeportes.png?alt=media&token=68f41473-9690-4797-81c7-4aa23fba129a',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FEcologia.png?alt=media&token=32cee825-e611-4846-9b8b-73294d41cbde',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FExpresion%20y%20Comunicacion.png?alt=media&token=cd24e091-95dc-40a6-bbd9-79eba9d3775b',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FHumanidades.png?alt=media&token=903feab7-c448-4478-aa46-c9853002e5eb',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FSeguridad%20y%20Rescate.png?alt=media&token=f336370b-ebdc-41ee-8744-d65d05ffdb04',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FTecnologia%20y%20Ciencia.png?alt=media&token=23f3e183-2287-4a7d-9cef-434ca31d2ad8',
        },
        rangos: {
            1: 'Piel',
            2: 'Bosque',
            3: 'Pradera',
            4: 'Recorrido',
        },
        especialidades: {
            1: 'Deportes',
            2: 'Ecología',
            3: 'Expresión y Comunicación',
            4: 'Humanidades',
            5: 'Seguridad y Rescate',
            6: 'Ciencia y Tecnología',
        },
    },
    {
        nombre:'Manada de Lobatos',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Manada%20de%20lobos.png?alt=media&token=e654ee2a-1f31-4fc1-a92b-e1671eeaf33d',
        promesa:{
            1:'YO PROMETO',
            1:'CUMPLIR CON AMOR',
            1:'MIS DEBERES PARA CON DIOS Y LA PATRIA',
            1:'OBEDECER LA LEY DE LA MANADA Y HACER UNA BUENA ACCION DIARIAMENTE.',
        },
        oración:'Dulce y buen Señor mío, enseñame a ser, humilde y bondadoso, a imitar tu ejemplo a amarte con todo mi corazón y a seguir el camino que me ha de llevar al cielo junto ante Ti. Así sea.',
        ley:{
            1:'El lobato siempre escucha al viejo',
            2:'El lobato se vence a si mismo.',
        },
        normas:{
            1:'El lobato siempre piensa primero en los demás',
            2:'El lobato siempre tiene los ojos y los oídos bien',
            3:'El lobato esta limpio',
            4:'El lobato es alegre',
            5:'El lobato dice la verdad',
        },
        somosTitulo: '¡Ser lobato trata de hacer todo tipo de cosas emocionantes!',
        somos:[
            {
                1:'Si tienes entre 7 y 11 años y te gusta tenere muchos amigos, hacer cosas nuevas, y sobre todo, tener un montón de diversión, la manada de lobatos es para tí!!',
                2:'La manada de lobatos es la sección del grupo scout conformada por niños entre 7 y 11 años donde conviven, juegan y aprenden.',
                3:'El programa scout de los lobatos ofrece muchas actividades divertidas para los castores, como manualidades, juegos, deportes, canciones e historias.',
                4:'Los lobatos forman parte de una manada integrada por niños de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada niño.',
                5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',
            },
        ],
        adelantoProgresivo:'La manada de lobatos cuenta con un adelanto progresivo, donde cada lobato alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima:',
        insigniaMaxima:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20lobatos%2FLobo%20Rampante.png?alt=media&token=f82b2837-7a67-470c-b52f-49c725e962eb',
        nombreInsigniaMaxima:'Lobo Rampante',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20lobatos%2FPiel%20Gris.png?alt=media&token=40160b26-08d4-4944-b63c-269183d9d895',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20lobatos%2FSeeonee.png?alt=media&token=21ef099c-7b0b-4d4a-996f-ff58378388d1',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20lobatos%2FKhanhiwara.png?alt=media&token=77092b78-74b3-49e4-9046-3cc013d42e5d',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20lobatos%2FLobo%20Rastreador.png?alt=media&token=ad0f88b7-f4a6-48c2-9f65-44e20b1d14fb',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FManada%20de%20lobatos%2FLobo%20Cazador.png?alt=media&token=804ae3e6-6c59-4f37-8cb8-22b6215eeb5e',
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FDeportes.png?alt=media&token=68f41473-9690-4797-81c7-4aa23fba129a',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FEcologia.png?alt=media&token=32cee825-e611-4846-9b8b-73294d41cbde',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FExpresion%20y%20Comunicacion.png?alt=media&token=cd24e091-95dc-40a6-bbd9-79eba9d3775b',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FHumanidades.png?alt=media&token=903feab7-c448-4478-aa46-c9853002e5eb',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FSeguridad%20y%20Rescate.png?alt=media&token=f336370b-ebdc-41ee-8744-d65d05ffdb04',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FManadas%2FTecnologia%20y%20Ciencia.png?alt=media&token=23f3e183-2287-4a7d-9cef-434ca31d2ad8',
        },
        rangos: {
            1: 'Piel',
            2: 'Seeonee',
            3: 'Khanhiwara',
            4: 'Lobo Rastreador',
            5: 'Lobo Cazador',
        },
        especialidades: {
            1: 'Deportes',
            2: 'Ecología',
            3: 'Expresión y Comunicación',
            4: 'Humanidades',
            5: 'Seguridad y Rescate',
            6: 'Ciencia y Tecnología',
        },
    },
    {
        nombre:'Tropa de Muchachas',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Tropa%20mujeres.png?alt=media&token=76893e7f-9775-424a-bb17-47e631fb4b9c',
        promesa:{
            1:'YO PROMETO POR MI HONOR',
            2:'HACER CUANTO DE MI DEPENDA',
            3:'PARA CUMPLIR MIS DEBERES',
            4:'PARA CON DIOS Y LA PATRIA',
            5:'AYUDAR AL PROJIMO EN TODA CIRCUNSTANCIA Y CUMPLIR FIELMENTE LA LEY SCOUT.',
        },
        oración:'Señor, enseñame a ser generosa, a servirte como lo mereces, a dar sin medida a combatir sin temor a que me hieran a trabajar sin descanso y a no buscar recompensa más que el saber que hago tu santa voluntad. Así sea.',
        ley:{
            1:'El scout cifra su honor en ser digno de confianza',
            2:'El scout es leal con su patria, sus padres, jefes, y subordinados',
            3:'El scout es útil y ayuda a los demás sin esperar recompensas',
            4:'El scout es amigo de todos y hermano de todo scout sin distincion de raza, credo, nacionalidad o razón social',
            5:'El scout es cortez y actua con nobleza',
            6:'El scout ve en la naturaleza la obra de Dios, protege a los animales y las plantas',
            7:'El scout obedece con responsabilidad y hace las cosas en orden y completas',
            8:'El scout ríe y canta en sus dificultades',
            9:'El scout es económico, trabajador y cuidadoso del bien ajeno',
            10:'El scout es limpio, sano y puro de pensamiento palabras y acciones',
        },
        normas:{},
        somosTitulo: 'Ser scout trata de hacer todo tipo de cosas emocionantes',
        somos:[
            {
                1:'Si tienes entre 11 y 16 años y te gusta tenere muchas amigas, hacer cosas nuevas, y sobre todo, tener un montón de diversión, la tropa de muchachas es para tí!!!',
                2:'La tropa de muchachas es la sección del grupo scout conformada por jovenes entre 11 y 16 años donde conviven, juegan y aprenden.',
                3:'El programa scout de los lobatos ofrece muchas actividades divertidas para los castores, como manualidades, juegos, deportes, canciones e historias.',
                4:'Los scouts forman parte de una tropa integrada por jovenes de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada muchacha.',
                5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',
            },
        ],
        adelantoProgresivo:'La tropa de muchachas cuenta con un adelanto progresivo, donde cada gacela alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima',
        insigniaMaxima:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FAveFenix.png?alt=media&token=29008576-6e7c-4ad8-9902-a501b7688f0e',
        nombreInsigniaMaxima:'Ave Fenix',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FExploradora.png?alt=media&token=9aba4d2d-b263-40b2-a369-f4f50efe65e9',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FExploradora.png?alt=media&token=9aba4d2d-b263-40b2-a369-f4f50efe65e9',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FDubhe.png?alt=media&token=a145739e-620e-42bb-97d6-d48564867bb6',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FMerak.png?alt=media&token=f094f269-4e19-4c28-84b1-2e2b59eb1003',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FSirius.png?alt=media&token=137b39bd-d647-417e-98d0-7a82b92a8625',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20muchachas%2FPolaris.png?alt=media&token=9b8f8d0f-77d7-4d16-9590-4960203665e0',
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FDeportes.png?alt=media&token=99088f43-6e10-479c-9309-fb2253f829f5',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FEcologia.png?alt=media&token=562a5bce-ecbb-44eb-8175-3d357871ed5c',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FExpresion%20y%20Comunicacion.png?alt=media&token=2c31cc87-fd00-40ec-80a6-3ff3f1e80118',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FHumanidades.png?alt=media&token=7314ad7b-6497-4681-a2c9-4c31623aa30f',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FSeguridad%20y%20Rescate.png?alt=media&token=1e5308f4-d62d-44a6-a96b-06091e8966f1',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTecnologia%20y%20Ciencia.png?alt=media&token=2d725efe-4c5d-497b-949d-c24ffc6e43a2',
        },
        rangos: {
            1: 'Exploradora',
            2: 'Pionera',
            3: 'Dubhe',
            4: 'Merak',
            5: 'Sirius',
            6: 'Polaris',
        },
        especialidades: {
            1: 'Deportes',
            2: 'Ecología',
            3: 'Expresión y Comunicación',
            4: 'Humanidades',
            5: 'Seguridad y Rescate',
            6: 'Ciencia y Tecnología',
        },
    },
    {
        nombre:'Tropa Scout',
        icono:"https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Tropa%20Scout.png?alt=media&token=6aa26c73-570f-4973-8bbd-ba9d9c2c534f",
        promesa: {
            1:'YO PROMETO POR MI HONOR,',
            2:'HACER CUANTO DE MI DEPENDA',
            3:'PARA CUMPLIR MIS DEBERES',
            4:'PARA CON DIOS Y LA PATRIA',
            5:'AYUDAR AL PROJIMO EN TODA CIRCUNSTANCIA Y CUMPLIR FIELMENTE LA LEY SCOUT.',
        },
        oración:'Señor, enseñame a ser generoso, a servirte como lo mereces, a dar sin medida a combatir sin temor a que me hieran a trabajar sin descanso y a no buscar recompensa más que el saber que hago tu santa voluntad. Así sea.',
        ley:{
            1:'El scout cifra su honor en ser digno de confianza',
            2:'El scout es leal con su patria, sus padres, jefes, y subordinados',
            3:'El scout es útil y ayuda a los demás sin esperar recompensas',
            4:'El scout es amigo de todos y hermano de todo scout sin distincion de raza, credo, nacionalidad o razón social',
            5:'El scout es cortez y actua con nobleza',
            6:'El scout ve en la naturaleza la obra de Dios, protege a los animales y las plantas',
            7:'El scout obedece con responsabilidad y hace las cosas en orden y completas',
            8:'El scout ríe y canta en sus dificultades',
            9:'El scout es económico, trabajador y cuidadoso del bien ajeno',
            10:'El scout es limpio, sano y puro de pensamiento palabras y acciones',
        },
        normas:{},
        somosTitulo: 'Ser scout trata de hacer todo tipo de cosas emocionantes',
        somos:[{
            1:'Si tienes entre 11 y 16 años y te gusta tener muchos amigos, hacer cosas nuevas, y sobre todo, tener un montón de diversión, la tropa scout!!!',
            2:'La tropa scout es la sección del grupo scout conformada por jovenes entre 11 y 16 años donde conviven, juegan y aprenden.',
            3:'El programa scout de los lobatos ofrece muchas actividades divertidas para los castores, como manualidades, juegos, deportes, canciones e historias.',
            4:'Los scouts forman parte de una tropa integrada por jovenes de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada muchacho.',
            5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',
        },],
        adelantoProgresivo:'La tropa scout cuenta con un adelanto progresivo, donde cada gacela alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima',
        insigniaMaxima:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FCaballero%20Scout%20Aguila.png?alt=media&token=8e2a7553-3238-49f3-b22a-b0a4d94999be',
        nombreInsigniaMaxima:'Caballero Scout Aguila',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FExplorador.png?alt=media&token=9f1f8bd2-206c-4aa0-a074-af2cc78ac877',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FPionero.png?alt=media&token=0518fda0-1807-4390-ac61-4559f497c498',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FAztlan.png?alt=media&token=d494a06f-0db2-4786-8dd3-c42ffc932a67',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FKontiki.png?alt=media&token=16f3b7a0-6407-4d4f-80ec-5caba2648c62',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FEverest.png?alt=media&token=dc6669a7-2df9-4644-8f1e-171487ba0797',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTropa%20de%20scouts%2FApolo.png?alt=media&token=cddb42a4-d691-47a6-aff2-b4b8dcdccedf',
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FDeportes.png?alt=media&token=99088f43-6e10-479c-9309-fb2253f829f5',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FEcologia.png?alt=media&token=562a5bce-ecbb-44eb-8175-3d357871ed5c',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FExpresion%20y%20Comunicacion.png?alt=media&token=2c31cc87-fd00-40ec-80a6-3ff3f1e80118',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FHumanidades.png?alt=media&token=7314ad7b-6497-4681-a2c9-4c31623aa30f',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FSeguridad%20y%20Rescate.png?alt=media&token=1e5308f4-d62d-44a6-a96b-06091e8966f1',
            6: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FTropas%2FTecnologia%20y%20Ciencia.png?alt=media&token=2d725efe-4c5d-497b-949d-c24ffc6e43a2',
        },
        rangos: {
            1: 'Explorador',
            2: 'Pionero',
            3: 'Aztlan',
            4: 'Kon-tiki',
            5: 'Everest',
            6: 'Apolo',
        },
        especialidades: {
            1: 'Deportes',
            2: 'Ecología',
            3: 'Expresión y Comunicación',
            4: 'Humanidades',
            5: 'Seguridad y Rescate',
            6: 'Ciencia y Tecnología',
        },
    },
    {
        nombre:'Clan de Precursoras',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Clan%20Percusores.png?alt=media&token=ebf1b6ac-1d50-46d0-bbbe-6a0d8cdc39b4',
        promesa: {
            1:'YO PROMETO POR MI HONOR,',
            2:'HACER CUANTO DE MI DEPENDA',
            3:'PARA CUMPLIR MIS DEBERES',
            4:'PARA CON DIOS Y LA PATRIA',
            5:'AYUDAR AL PROJIMO EN TODA CIRCUNSTANCIA Y CUMPLIR FIELMENTE LA LEY SCOUT.',
        },
        oración:'Dame Señor: Un corazón vigilante que ningun pensamiento vano me aleje de un corazón noble que ningun afecto indigno rebaje, un corazón recto que ninguna maldad desvíe, un corazón fuerte que ninguna pasión esclavise, un corazón generoso para servir. Así sea.',
        ley:{
            1:'El scout cifra su honor en ser digno de confianza',
            2:'El scout es leal con su patria, sus padres, jefes, y subordinados',
            3:'El scout es útil y ayuda a los demás sin esperar recompensas',
            4:'El scout es amigo de todos y hermano de todo scout sin distincion de raza, credo, nacionalidad o razón social',
            5:'El scout es cortez y actua con nobleza',
            6:'El scout ve en la naturaleza la obra de Dios, protege a los animales y las plantas',
            7:'El scout obedece con responsabilidad y hace las cosas en orden y completas',
            8:'El scout ríe y canta en sus dificultades',
            9:'El scout es económico, trabajador y cuidadoso del bien ajeno',
            10:'El scout es limpio, sano y puro de pensamiento palabras y acciones',
        },
        normas:{},
        somosTitulo: '¡Ser precursora trata de hacer todo tipo de cosas emocionantes!',
        somos:[{
            1:'Si tienes entre 17 y 22 años y te gusta tenere muchas amigas, hacer cosas nuevas, y sobre todo, tener un montón de diversión, el clan de precursoras es para tí!!!',
            2:'El clan de precursoras es la sección del grupo scout conformada por jovenes entre 17 y 22 años donde conviven, juegan y aprenden.',
            3:'El programa scout de los precursoras ofrece muchas actividades divertidas para los precursoras, como manualidades, juegos, deportes, canciones e historias.',
            4:'Los precursoras forman parte de una tropa integrada por jovenes de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada muchacho.',
            5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',
        },],
        adelantoProgresivo:'El clan de precursoras cuenta con un adelanto progresivo, donde cada gacela alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima:',
        insigniaMaxima:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FBP%20Precursora.png?alt=media&token=0a6a5843-08e4-477c-b789-5c0d0d5ebbca',
        nombreInsigniaMaxima:'BP Precursora',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FProyectos.png?alt=media&token=f438d23b-fb95-40f4-9419-327cf6564433',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FSer.png?alt=media&token=1df3bd8d-5f98-47e6-8c40-805c95fbab0a',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FEncuentro.png?alt=media&token=2694cad4-6fac-4dd7-8830-79b934988213',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FEspecialidad.png?alt=media&token=6a5ced97-3f9b-4bcb-b063-e98d8c597a65',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FTecnica.png?alt=media&token=24304a8c-54ea-4ce6-8138-c98477c3caf6',
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FTecnica.png?alt=media&token=24304a8c-54ea-4ce6-8138-c98477c3caf6',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FExpediciones.png?alt=media&token=1db8baad-5126-445e-aa11-11563c548643',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FProyectos.png?alt=media&token=f438d23b-fb95-40f4-9419-327cf6564433',
        },
        rangos: {
            1: 'Saeta',
            2: 'Ser',
            3: 'Encuentro',
            4: 'Especialidad',
            5: 'Precursora',
        },
        especialidades:{
            1: 'Tecnica',
            2: 'Expediciones',
            3: 'Proyectos',
        },
    },
    {
        nombre:'Clan de Rovers',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Clan%20Robers.png?alt=media&token=c5564d43-9191-4421-bef8-6cf809fbf0bf',
        promesa: {
            1:'YO PROMETO POR MI HONOR,',
            2:'HACER CUANTO DE MI DEPENDA',
            3:'PARA CUMPLIR MIS DEBERES',
            4:'PARA CON DIOS Y LA PATRIA',
            5:'AYUDAR AL PROJIMO EN TODA CIRCUNSTANCIA Y CUMPLIR FIELMENTE LA LEY SCOUT.',
        },
        oración:'Dame Señor: Un corazón vigilante que ningun pensamiento vano me aleje de un corazón noble que ningun afecto indigno rebaje, un corazón recto que ninguna maldad desvíe, un corazón fuerte que ninguna pasión esclavise, un corazón generoso para servir. Así sea.',
        ley:{
            1:'El scout cifra su honor en ser digno de confianza',
            2:'El scout es leal con su patria, sus padres, jefes, y subordinados',
            3:'El scout es útil y ayuda a los demás sin esperar recompensas',
            4:'El scout es amigo de todos y hermano de todo scout sin distincion de raza, credo, nacionalidad o razón social',
            5:'El scout es cortez y actua con nobleza',
            6:'El scout ve en la naturaleza la obra de Dios, protege a los animales y las plantas',
            7:'El scout obedece con responsabilidad y hace las cosas en orden y completas',
            8:'El scout ríe y canta en sus dificultades',
            9:'El scout es económico, trabajador y cuidadoso del bien ajeno',
            10:'El scout es limpio, sano y puro de pensamiento palabras y acciones',
        },
        normas:{},
        somosTitulo: '¡Ser precursora trata de hacer todo tipo de cosas emocionantes!',
        somos:[{
            1:'Si tienes entre 17 y 22 años y te gusta tener muchos amigos, hacer cosas nuevas, y sobre todo, tener un montón de diversión, el clan de rovers es para tí!!!',
            2:'El clan de rovers es la sección del grupo scout conformada por jovenes entre 17 y 22 años donde conviven, juegan y aprenden.',
            3:'El programa scout del clan de rovers ofrece muchas actividades divertidas para los precursoras, como manualidades, juegos, deportes, canciones e historias.',
            4:'Los Scouts del clan rovers forman parte de una tropa integrada por jovenes de la edad y unos lideres adultos que se preparan para brindar lo mejor a cada muchacho.',
            5:'Las reuniones son cada sabado. Y estas van desde actividades en el local hasta excursiones y campamentos.',

        },],
        adelantoProgresivo:'El clan de rovers cuenta con un adelanto progresivo, donde cada gacela alcanza metas especificas y obtendran conforme va avanzando las siguientes insignias para concluir su etapa con la insignia maxima:',
        insigniaMaxima:'/img/Insignias/Clanes/Clan de Rovers/BPRover.png',
        nombreInsigniaMaxima:'BP Rover',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20rovers%2FProyectos.png?alt=media&token=e7818f7e-f94e-48db-9426-f47f0e0d2258',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20rovers%2FSer.png?alt=media&token=0dcda57c-f38a-460f-bff9-054de1ea8065',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20rovers%2FEncuentro.png?alt=media&token=189dd823-c199-406c-9052-077bd4042e64',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20rovers%2FEspecialidad.png?alt=media&token=6f0be8a8-a294-4778-80a1-3c8abf685b6c',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20rovers%2FCharreteras.png?alt=media&token=4bd6dac2-c73a-48bc-a5e0-c8156199840f',
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FTecnica.png?alt=media&token=24304a8c-54ea-4ce6-8138-c98477c3caf6',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FExpediciones.png?alt=media&token=1db8baad-5126-445e-aa11-11563c548643',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FProyectos.png?alt=media&token=f438d23b-fb95-40f4-9419-327cf6564433',
        },
        rangos: {
            1: 'Escudero',
            2: 'Ser',
            3: 'Encuentro',
            4: 'Especialidad',
            5: 'Chatarrera Rover',
        },
        especialidades: {
            1: 'Tecnica',
            2: 'Expediciones',
            3: 'Proyectos',
        },
    },
    {
        nombre:'Scouters y Dirigentes',
        icono:'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Scouters.png?alt=media&token=3eb8a513-014b-4499-b4c1-6e4229625c50',
        promesa: {
            1:'YO PROMETO POR MI HONOR,',
            2:'HACER CUANTO DE MI DEPENDA',
            3:'PARA CUMPLIR MIS DEBERES',
            4:'PARA CON DIOS Y LA PATRIA',
            5:'AYUDAR AL PROJIMO EN TODA CIRCUNSTANCIA Y CUMPLIR FIELMENTE LA LEY SCOUT.',
        },
        oración:'Señor y jefe mío, que a pesar de mis debilidades me has escogido como jefe y guardian de mis hermanos scouts. Haz que mis palabras y mis ejemplos iluminen su camino por es sendero de tu ley, que sepa mostrarles tu huella divina en la naturaleza que has creado, enseñarles lo que debo, y conducirlos de etapa en etapa hasta Ti, Señor mío, en el campo del reposo y de la dicha, donde has establecido tu tienda y la nuentra por todo la eternidad. Así sea.',
        ley:{
            1:'El scout cifra su honor en ser digno de confianza',
            2:'El scout es leal con su patria, sus padres, jefes, y subordinados',
            3:'El scout es útil y ayuda a los demás sin esperar recompensas',
            4:'El scout es amigo de todos y hermano de todo scout sin distincion de raza, credo, nacionalidad o razón social',
            5:'El scout es cortez y actua con nobleza',
            6:'El scout ve en la naturaleza la obra de Dios, protege a los animales y las plantas',
            7:'El scout obedece con responsabilidad y hace las cosas en orden y completas',
            8:'El scout ríe y canta en sus dificultades',
            9:'El scout es económico, trabajador y cuidadoso del bien ajeno',
            10:'El scout es limpio, sano y puro de pensamiento palabras y acciones',
        },
        normas:{},
        somosTitulo: 'Es más gratificante saber que estoy haciendo una diferencia positiva en las vidas de los niños ayudandoles a ser lo mejor posible',
        somos:[{
            1:'Si eres mayor de 22 años y te gusta brindarte a los demás, las puertas estan abiertas para colaborar en algún grupo scout de tu región. Al ingresar se te brindará todo el apoyo necesario para que te capacites y puedas brindar lo mejor de ti.',
            2:'Los Scoutters son aquellos voluntarios que trabajan directamente con los muchachos en el grupo Scout. Los dirigentes son aquellos voluntarios que hacen posible el buen funcionamiento del grupo Scout.',
            3:'Los grupos Scout de mayor éxito, son aquellos en los que existe un fuerte apoyo de los adultos. Los Scoutters y los dirigentes son voluntarios entusiastas y dedicados. Hombres y mujeres de todas las clases sociales que comparten un amor por la aventura y el deseo de enriquecer la vida de los jovenes.',
            4:'Hay muchas maneras de colaborar, desde ser un buen difusor y promotor del escultismo, ser padre de familia que apoya el movimiento, prestar sus servicios para las labores administrativas de los grupos o bien enrolarse como scoutter y prepararse para estar al frente de los muchachos.',
        },],
        adelantoProgresivo:'Los scoutters y dirigentes provienen de todos lados, desde los padres de los scouts, scouts de infancia, o personas sin experiencia en los scouts! Pero muy motivados en capacitarse para brindarse a los demás.',
        insigniaMaxima:'',
        nombreInsigniaMaxima:'Cargo Dirigentes',
        rangosIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FScouters%2FCargo%20Castores.png?alt=media&token=e2686fc4-7093-4cef-90bd-ff851f656ef8',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FScouters%2FCargo%20Manadas.png?alt=media&token=fb358434-b859-448f-8c13-1710d62a0b24',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FScouters%2FCargo%20Tropas.png?alt=media&token=f26b1a99-153f-48f2-89c0-750a574619b6',
            4: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FScouters%2FCargo%20Clanes.png?alt=media&token=94f6330b-c8c5-43ce-96ee-549be2c429cd',
            5: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FScouters%2FCargo%20Clanes.png?alt=media&token=94f6330b-c8c5-43ce-96ee-549be2c429cd',
            
        },
        especialidadesIconos:{
            1: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FTecnica.png?alt=media&token=24304a8c-54ea-4ce6-8138-c98477c3caf6',
            2: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FExpediciones.png?alt=media&token=1db8baad-5126-445e-aa11-11563c548643',
            3: 'https://firebasestorage.googleapis.com/v0/b/agsmac-6f212.appspot.com/o/Insignias%2FClanes%2FClan%20de%20percusoras%2FProyectos.png?alt=media&token=f438d23b-fb95-40f4-9419-327cf6564433',
        },
        rangos: {
            1: 'Escudero',
            2: 'Ser',
            3: 'Encuentro',
            4: 'Especialidad',
            5: 'Chatarrera Rover',
        },
        especialidades: {
            1: 'Tecnica',
            2: 'Expediciones',
            3: 'Proyectos',
        },
    },

];

export default tropas; 